# 鸢尾花数据集

快速了解鸢尾花数据集：
https://www.bilibili.com/video/BV1Ut411n78Z

In [1]:
from sklearn.datasets import load_iris, fetch_20newsgroups, fetch_openml
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score

In [2]:
#鸢尾花数据集，查看特征，目标，样本量

li = load_iris()

print("获取特征值")
print(type(li.data))
print(li.data)
print(li.data.shape)
print("目标值")
print(li.target)
print('-' * 50)
print(li.DESCR)
print('-' * 50)
print(li.feature_names)  # 重点
print('-' * 50)
print(li.target_names)
print('-' * 50)

获取特征值
<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 

In [3]:
# 默认是乱序的,random_state为了确保两次的随机策略一致，往往会带上
# 训练集的特征向量，测试集的特征向量，训练集的目标，测试集的目标
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
x_train, x_test, y_train, y_test = train_test_split(li.data, li.target, test_size=0.25, random_state=1)
# 测试集占比 25%

print("训练集特征值和目标值：", x_train, y_train)
print("训练集特征值shape", x_train.shape)

print("测试集特征值和目标值：", x_test, y_test)
print("测试集特征值shape", x_test.shape)

训练集特征值和目标值： [[6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [6.  2.2 5.  1.5]
 [6.3 2.9 5.6 1.8]
 [6.6 2.9 4.6 1.3]
 [7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]
 [5.1 3.4 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [7.3 2.9 6.3 1.8]
 [6.4 2.8 5.6 2.2]
 [6.2 2.8 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [6.7 3.3 5.7 2.1]
 [4.4 3.  1.3 0.2]
 [6.  2.7 5.1 1.6]
 [6.4 2.7 5.3 1.9]
 [5.9 3.  5.1 1.8]
 [5.2 3.5 1.5 0.2]
 [5.1 3.3 1.7 0.5]


# 20 类新闻数据集

In [4]:
# 下面是比较大的数据，需要下载一会，20类新闻
news = fetch_20newsgroups(subset='all', data_home='data')
# print(news.feature_names)  #这个没有
print(news.DESCR)
print('-' * 50)
print(news.data[0])
print(news.target[0])
print(len(news.data))
print('-' * 50)
print(news.target)
print(min(news.target), max(news.target))


.. _20newsgroups_dataset:

The 20 newsgroups text dataset
------------------------------

The 20 newsgroups dataset comprises around 18000 newsgroups posts on
20 topics split in two subsets: one for training (or development)
and the other one for testing (or for performance evaluation). The split
between the train and test set is based upon a messages posted before
and after a specific date.

This module contains two loaders. The first one,
:func:`sklearn.datasets.fetch_20newsgroups`,
returns a list of the raw texts that can be fed to text feature
extractors such as :class:`~sklearn.feature_extraction.text.CountVectorizer`
with custom parameters so as to extract feature vectors.
The second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,
returns ready-to-use features, i.e., it is not necessary to use a feature
extractor.

**Data Set Characteristics:**

=================   ==========
Classes                     20
Samples total            18846
Dimensionality               1

# boston 房价数据集

这个数据集因为一些政治不正确的原因被官方删除了，因此需要一些替代手段。

> The Boston housing prices dataset has an ethical problem: asinvestigated in [1], the authors of this dataset engineered anon-invertible variable "B" assuming that racial self-segregation had apositive impact on house prices [2]. Furthermore the goal of theresearch that led to the creation of this dataset was to study theimpact of air quality but it did not give adequate demonstration of thevalidity of this assumption.

In [5]:
# from sklearn.datasets import load_boston
# 接着来看回归的数据,是波士顿房价

import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

# lb = load_boston()

print("获取特征值")
print(data[0])
print(data.shape)
print('-' * 50)
print("目标值")
print(target)
# print(lb.DESCR)
# print(lb.feature_names)
print('-' * 50)
# 回归问题没这个,打印这个会报错
# print(lb.target_names)

获取特征值
[6.320e-03 1.800e+01 2.310e+00 0.000e+00 5.380e-01 6.575e+00 6.520e+01
 4.090e+00 1.000e+00 2.960e+02 1.530e+01 3.969e+02 4.980e+00]
(506, 13)
--------------------------------------------------
目标值
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1

# 分类估计器

在 sklearn 中，估计器(estimator)是一个重要的角色，分类器和回归器都属于 estimator，是一类实现了算法的 API.

用于分类的估计器：
- ``sklearn.neighbors`` k-近邻算法
- ``sklearn.naive_bayes`` 朴素贝叶斯
- ``sklearn.linear_model.LogisticRegression`` 逻辑回归
- ``sklearn.tree`` 决策树与随机森林

用于回归的估计器：
- ``sklearn.linear_model.LinearRegression`` 线性回归
- ``sklearn.linear_model.Ridge`` 岭回归

估计器的工作流程：

![pic1](./1.png)

# knn

下面简单介绍 k 近邻算法，此算法在 [人工智能导论](https://dropsong.github.io/posts/6f3f8819.html) 中亦有记载。

算法的思想是：如果一个样本在特征空间中与其最相似的 k 个（即特征空间中最邻近）样本大多数属于某一个类别，则该样本也属于这个类别。

**接下来看一个 k 近邻算法实例 - 预测入住位置** ：
https://www.kaggle.com/c/facebook-v-predicting-check-ins

下面的代码只是一个非常简单的版本，并且极大地缩小了数据集范围。

In [6]:
# K近邻
"""
K-近邻预测用户签到位置
:return:None
"""
# 读取数据
data = pd.read_csv("./data/train.csv")

print(data.head(10))
print(data.shape)
# 处理数据
# 1、缩小数据,查询数据,为了减少计算时间
data = data.query("x > 1.0 &  x < 1.25 & y > 2.5 & y < 2.75")

# 处理时间的数据
time_value = pd.to_datetime(data['time'], unit='s')

print(time_value)  # 最大时间是1月10号
#
# 把日期格式转换成 字典格式，把年，月，日，时，分，秒转换为字典格式，
time_value = pd.DatetimeIndex(time_value)
#
print('-' * 50)
print(time_value)
print('-' * 50)
# 构造一些特征，执行的警告是因为我们的操作是复制，loc是直接放入
print(type(data))
# data['day'] = time_value.day
# data['hour'] = time_value.hour
# data['weekday'] = time_value.weekday
#日期，是否是周末，小时对于个人行为的影响是较大的
data.insert(data.shape[1], 'day', time_value.day)
data.insert(data.shape[1], 'hour', time_value.hour)
data.insert(data.shape[1], 'weekday', time_value.weekday)

#
# 把时间戳特征删除
data = data.drop(['time'], axis=1)
print('-' * 50)
print(data)
#
# 把签到数量少于n个目标位置删除
place_count = data.groupby('place_id').count()
# 把index变为0,1,2，3,4,5,6这种效果，从零开始拍，原来的index是地点
# 只选择去的人大于3的数据，认为1,2,3的是噪音
tf = place_count[place_count.row_id > 3].reset_index()
# 根据设定的地点目标值，对原本的样本进行过滤
data = data[data['place_id'].isin(tf.place_id)]
print(data)
# # 取出数据当中的特征值和目标值
y = data['place_id']
# 删除目标值，保留特征值，
x = data.drop(['place_id'], axis=1)
# 删除无用的特征值
x = x.drop(['row_id'], axis=1)
print('x.shapes = ')
print(x.shape)
print('x.columns = ')
print(x.columns)
# 进行数据的分割训练集合测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

# 特征工程（标准化）,下面3行注释，一开始我们不进行标准化，看下效果，目标值要不要标准化？
std = StandardScaler()
# #
# # # 对测试集和训练集的特征值进行标准化,服务于knn fit
x_train = std.fit_transform(x_train)
# # transform返回的是copy，不在原有的输入对象中去修改
# print(id(x_test))
print(std.mean_)
print(std.var_)
x_test = std.transform(x_test)  #transfrom不再进行均值和方差的计算，是在原有的基础上去标准化
print('-' * 50)
# print(id(x_test))
print(std.mean_)
print(std.var_)
# # 进行算法流程 # 超参数，可以通过设置n_neighbors=5，来调整结果好坏
knn = KNeighborsClassifier(n_neighbors=5)

# # fit， predict,score，训练
knn.fit(x_train, y_train)
# # #
# # # 得出预测结果
y_predict = knn.predict(x_test)
# #
print("预测的目标签到位置为：", y_predict)
# # #
# # # # 得出准确率
print("预测的准确率:", knn.score(x_test, y_test))

   row_id       x       y  accuracy    time    place_id
0       0  0.7941  9.0809        54  470702  8523065625
1       1  5.9567  4.7968        13  186555  1757726713
2       2  8.3078  7.0407        74  322648  1137537235
3       3  7.3665  2.5165        65  704587  6567393236
4       4  4.0961  1.1307        31  472130  7440663949
5       5  3.8099  1.9586        75  178065  6289802927
6       6  6.3336  4.3720        13  666829  9931249544
7       7  5.7409  6.7697        85  369002  5662813655
8       8  4.3114  6.9410         3  166384  8471780938
9       9  6.3414  0.0758        65  400060  1253803156
(29118021, 6)
600        1970-01-01 18:09:40
957        1970-01-10 02:11:10
4345       1970-01-05 15:08:02
4735       1970-01-06 23:03:03
5580       1970-01-09 11:26:50
                   ...        
29100203   1970-01-01 10:33:56
29108443   1970-01-07 23:22:04
29109993   1970-01-08 15:03:14
29111539   1970-01-04 00:53:41
29112154   1970-01-08 23:01:07
Name: time, Length: 17710, dt

k 值取多大？有什么影响？
- k 值取很小：容易受异常点影响
- k 值取很大：容易受最近数据太多导致比例变化

In [7]:
print(max(time_value))

1970-01-10 02:23:38


k-近邻算法优点：
- 简单有效
- 重新训练的代价低
- 适合类域交叉样本
  - KNN 方法主要靠周围有限的邻近的样本，而不是靠判别类域的方法来确定所属类别的，因此对于类域的交叉或重叠较多的待分样本集来说，KNN 方法较其他方法更为适合。
- 适合大样本自动分类
  - 该算法比较适用于样本容量比较大的类域的自动分类，而那些样本容量较小的类域采用这种算法比较容易产生误分。

k-近邻算法缺点：
- 惰性学习
  - KNN 算法是懒散学习方法（lazy learning,基本上不学习），一些积极学习的算法要快很多
- 类别评分不是规格化（没有严格的数学推导）
- 输出可解释性不强（例如决策树的输出可解释性就较强）
- 对不均衡的样本不擅长
  - 当样本不平衡时，如一个类的样本容量很大，而其他类样本容量很小时，有可能导致当输入一个新样本时，该样本的 K 个邻居中大容量类的样本占多数。该算法只计算“最近的”邻居样本，某一类的样本数量很大，那么或者这类样本并不接近目标样本，或者这类样本很靠近目标样本。无论怎样，数量并不能影响运行结果。可以采用权值的方法（和该样本距离小的邻居权值大）来改进。
- 计算量较大
  - 目前常用的解决方法是事先对已知样本点进行裁剪，事先去除对分类作用不大的样本。

k-近邻算法实现：加快搜索速度——基于算法的改进 **KDTree**, API 接口里面有实现。

# 网格搜索

此内容在 [人工智能导论](https://dropsong.github.io/posts/6f3f8819.html) 中亦有记载。搜索“k-折交叉验证（K-CV）”

In [8]:
# 构造一些参数的值进行搜索
param = {"n_neighbors": [3, 5, 10, 12, 15]}

# 进行网格搜索，cv=3是3折交叉验证，用其中2折训练，1折验证
gc = GridSearchCV(knn, param_grid=param, cv=3)

gc.fit(x_train, y_train)  # 你给它的x_train，它又分为训练集，验证集

# 预测准确率，为了给大家看看
print("在测试集上准确率：", gc.score(x_test, y_test))

print("在交叉验证当中最好的结果：", gc.best_score_)

print("选择最好的模型是：", gc.best_estimator_)

print("每个超参数每次交叉验证的结果：", gc.cv_results_)

/home/zhiyue/Documents/myvenv/mlvenv/lib/python3.11/site-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


在测试集上准确率： 0.47966903073286055
在交叉验证当中最好的结果： 0.4596467484726366
选择最好的模型是： KNeighborsClassifier(n_neighbors=10)
每个超参数每次交叉验证的结果： {'mean_fit_time': array([0.00663495, 0.00570822, 0.00563606, 0.00566483, 0.00570917]), 'std_fit_time': array([1.30730368e-03, 1.65227114e-05, 6.12806352e-05, 4.42359101e-05,
       5.66617525e-05]), 'mean_score_time': array([0.08330512, 0.08822219, 0.10076253, 0.10499819, 0.11136285]), 'std_score_time': array([0.00067103, 0.0002986 , 0.00023517, 0.00053634, 0.00021282]), 'param_n_neighbors': masked_array(data=[3, 5, 10, 12, 15],
             mask=[False, False, False, False, False],
       fill_value=999999), 'params': [{'n_neighbors': 3}, {'n_neighbors': 5}, {'n_neighbors': 10}, {'n_neighbors': 12}, {'n_neighbors': 15}], 'split0_test_score': array([0.44468085, 0.4607565 , 0.46170213, 0.45650118, 0.45508274]), 'split1_test_score': array([0.43390873, 0.45660913, 0.45542681, 0.45329865, 0.44809648]), 'split2_test_score': array([0.43982029, 0.45684559, 0.4618113 , 

# 分类模型的评估

## 基础知识

前置知识 [参考此处](https://dropsong.github.io/posts/6f3f8819.html#%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0) 。

**精确率(Precision)**：预测结果为正例样本中真实为正例的比例（**查得准**），TP/(TP+FP)

**召回率**：真实为正例的样本中预测结果为正例的比例（**查的全，对正样本的区分能力**），TP/(TP+FN)
- 医院非常重视召回率

**F1-score**，综合考虑了精确率和召回率，反映了模型的**稳健型**

$$
F_1 = \frac{2 TP}{2 TP + FN + FP} = \frac{2 \cdot Precision \cdot Recall}{Precision + Recall}
$$

## ROC 曲线与 AUC 值概述

**AUC（Area Under roc Curve）** 是一种用来度量分类模型好坏的一个标准。这样的标准其实有很多，例如：大约 10 年前在 machine learning 文献中一统天下的标准：分类精度；在信息检索(IR)领域中常用的 recall 和 precision，等等。其实，度量反应了人们对”好”的分类结果的追求，同一时期的不同的度量反映了人们对什么是”好”这个最根本问题的不同认识，而不同时期流行的度量则反映了人们认识事物的深度的变化。

近年来，随着 machine learning 的相关技术从实验室走向实际应用，一些实际的问题对度量标准提出了新的需求。特别的，现实中样本在不同类别上的不均衡分布(class distribution imbalance problem)。使得 accuracy 这样的传统的度量标准不能恰当的反应分类器的 performance。举个例子：测试样本中有A类样本 90 个，B 类样本 10 个。分类器 C1 把所有的测试样本都分成了 A 类，分类器 C2 把 A 类的 90 个样本分对了 70 个，B 类的 10 个样本分对了 5 个。则 C1 的分类精度为 90%，C2 的分类精度为 75% 。但是，显然 C2 更有用些。另外，在一些分类问题中犯不同的错误代价是不同的(cost sensitive learning)。这样，默认 0.5 为分类阈值的传统做法也显得不恰当了。

为了解决上述问题，人们从医疗分析领域引入了一种新的分类模型 performance 评判方法，ROC 分析。ROC 分析本身就是一个很丰富的内容，有兴趣的读者可以自行 Google，这里只做些简单的概念性的介绍。

ROC 的全名叫做 Receiver Operating Characteristic，其主要分析工具是一个画在二维平面上的曲线，ROC curve. 平面的横坐标是 false positive rate(FPR)，纵坐标是 true positive rate(TPR)。对某个分类器而言，我们可以根据其在测试样本上的表现得到一个 TPR 和 FPR 点对。这样，此分类器就可以映射成 ROC 平面上的一个点。调整这个分类器分类时候使用的阈值，我们就可以得到一个经过(0, 0)，(1, 1)的曲线，这就是此分类器的 ROC 曲线。一般情况下，这个曲线都应该处于(0, 0)和(1, 1)连线的上方。因为(0, 0)和(1, 1)连线形成的 ROC 曲线实际上代表的是一个随机分类器。如果很不幸，你得到一个位于此直线下方的分类器的话，一个直观的补救办法就是把所有的预测结果反向，即：分类器输出结果为正类，则最终分类的结果为负类，反之，则为正类。虽然，用 ROC curve 来表示分类器的 performance 很直观好用。可是，人们总是希望能有一个数值来标志分类器的好坏。于是 Area Under roc Curve(AUC) 就出现了。顾名思义，AUC 的值就是处于 ROC curve 下方的那部分面积的大小。通常，AUC 的值介于 0.5 到 1.0 之间，**较大的 AUC 代表了较好的 performance.**

## ROC 的动机

对于 01 两类分类问题，一些分类器得到的结果往往不是 01 这样的标签，如神经网络得到诸如 0.5，0.8 这样的分类结果。这时，我们人为取一个阈值，比如 0.4，那么小于 0.4 的归为 0 类，大于等于 0.4 的归为 1 类，可以得到一个分类结果。同样，这个阈值我们可以取 0.1 或 0.2 等等。取不同的阈值，最后得到的分类情况也就不同。如下面这幅图：

![pic2](./2.png)

蓝色表示原始为负类分类得到的统计图，红色表示原始为正类得到的统计图。那么我们取一条直线，直线左边分为负类，直线右边分为正类，这条直线也就是我们所取的阈值。阈值不同，可以得到不同的结果，但是由分类器决定的统计图始终是不变的。这时候就需要一个独立于阈值，只与分类器有关的评价指标，来衡量特定分类器的好坏。还有在类不平衡的情况下，如正样本有 90 个，负样本有 10 个，直接把所有样本分类为正样本，得到识别率为 90%，但这显然是没有意义的。如上就是 ROC 曲线的动机。

## ROC 的定义

ROC 曲线最初是运用在军事上，当前在医学领域使用非常广泛，因此指标称“阴性”，“阳性”。

| 名词     | 说明                                                                 |
|----------|----------------------------------------------------------------------|
| 特异性   | 阴性人群中，检测出阴性的几率。也称真阴性率。                        |
| 误报率   | 阴性人群中，检测为阳性的几率。也称假阳性率。（1-特异性）         |
| 敏感度   | 阳性人群中，检测出阳性的几率。也称真阳性率。                        |
| 假阴性率 | 阳性人群中，检测为阴性的几率。也称假阴性率。                        |

ROC 曲线的绘制是对所有测试样本的“误报率”以及“敏感度”绘制曲线。取**不同阈值时**对每个样本计算的 “误报率”**（假阳）作为 X 轴坐标**，“敏感度”**（真阳）作为 Y 轴坐标**。

因为样本的“误报率”（假阳）越小越好，“敏感度”（真阳）越大越好，即 X 坐标越小越好，Y 坐标越大越好，因此绘制的 ROC 曲线越靠近象限左上角越好。

## ROC 的图形化表示

![pic3](./3.png)

我们可以看出：左上角的点（TPR=1，FPR=0），为完美分类，也就是这个医生医术高明，诊断全对；点A（TPR>FPR），医生A的判断大体是正确的。中线上的点B（TPR=FPR），也就是医生B全都是蒙的，蒙对一半，蒙错一半；下半平面的点C（TPR<FPR），这个医生说你有病，那么你很可能没有病，医生C的话我们要反着听，为真庸医。

**上图中一个阈值，得到一个点。**现在我们**需要一个独立于阈值的评价指标**来衡量这个医生的医术如何，也就是遍历所有的阈值，得到ROC曲线。还是一开始的那幅图，假设如下就是某个医生的诊断统计图，直线代表阈值。我们遍历所有的阈值，能够在ROC平面上得到如下的ROC曲线。

![pic4](./4.png)

曲线距离左上角越近，证明分类器效果越好。

![pic5](./5.png)

如上，是三条ROC曲线，在0.23处取一条直线。那么，在同样的FPR=0.23的情况下，红色分类器得到更高的TPR。也就表明，ROC越往上，分类器效果越好。我们用一个标量值AUC来量化它。

## AUC 值

AUC 值为 ROC 曲线所覆盖的区域面积，显然，AUC 越大，分类器分类效果越好。
- ``AUC = 1``，是完美分类器，采用这个预测模型时，不管设定什么阈值都能得出完美预测。绝大多数预测的场合，不存在完美分类器。
- ``0.5 < AUC < 1``，优于随机猜测。这个分类器（模型）妥善设定阈值的话，能有预测价值。
- ``AUC = 0.5``，跟随机猜测一样（例：丢铜板），模型没有预测价值。
- ``AUC < 0.5``，比随机猜测还差；但只要总是反预测而行，就优于随机猜测。

**AUC 值的物理意义：**
假设分类器的输出是样本属于正类的socre（置信度），则AUC的物理意义为，任取一对（正、负）样本，正样本的score大于负样本的score的概率。

**AUC 值的计算：**
1. 第一种方法：AUC为ROC曲线下的面积，那我们直接计算面积可得。面积为一个个小的梯形面积之和，计算的精度与阈值的精度有关。
2. 第二种方法：根据AUC的物理意义，我们计算正样本score大于负样本的score的概率。取 ``N*M``（N为正样本数，M为负样本数）个二元组，比较score，最后得到AUC。时间复杂度为 $O(NM)$ 。
3. 第三种方法：与第二种方法相似，直接计算正样本score大于负样本的score的概率。我们首先把所有样本按照score排序，依次用rank表示他们，如最大score的样本，rank=n(n=N+M)，其次为n-1。那么对于正样本中rank最大的样本（rank_max），有M-1个其他正样本比他score小，那么就有(rank_max-1)-(M-1)个负样本比他score小。其次为(rank_second-1)-(M-2)。最后我们得到正样本大于负样本的概率为：
    $$
    \frac{\sum_{\text{所有正样本}} \mathrm{rank} - M(M+1) / 2}{M \cdot N}
    $$
时间复杂度为 O(N+M).

# 朴素贝叶斯进行文本分类

注意，[主观贝叶斯](https://dropsong.github.io/posts/6f3f8819.html#%E4%B8%8D%E7%A1%AE%E5%AE%9A%E6%80%A7%E6%8E%A8%E7%90%86)和**朴素贝叶斯**是不同的概念。

考虑这样的需求，我们需要对文章分类。根据一篇文章中出现的词，大致推断这是什么文章（科技、娱乐、...）。

$$
P(C | W) = \frac{P( W | C)P(C)}{P(W)}
$$

其中，W 为给定文档的特征值（频数统计,预测文档提供），$C$ 为文档类别。

假设训练集统计结果（指定统计词频）如下：

| 特征\统计 | 科技 | 娱乐 | 汇总（求和） |
| --- | --- | --- | --- |
| “商场” | 9 | 51 | 60 |
| “影院” | 8 | 56 | 64 |
| “支付宝” | 20 | 15 | 35 |
| “云计算” | 63 | 0 | 63 |
| 汇总(求和)  | 100 | 121 | 221 |

现有一篇被预测文档：出现了影院，支付宝，云计算，计算属于科技、娱乐的类别概率？

科技：

$$
P(\text{影院，支付宝，云计算} | \text{科技}) \cdot P(\text{科技}) = \frac{8}{100} \cdot \frac{20}{100} \cdot \frac{63}{100} \cdot (\frac{100}{221})
$$

娱乐：

$$
P(\text{影院，支付宝，云计算} | \text{娱乐}) \cdot P(\text{娱乐}) = \frac{56}{121} \cdot \frac{15}{121} \cdot \frac{0}{121} \cdot (\frac{121}{221}) = 0
$$

问题：**若属于某个类别为 0，合适吗？**

上面的例子我们得到娱乐概率为 0，这是**不合理**的，如果词频列表里面有很多出现次数都为 0，很可能计算结果都为零。

解决方法：**拉普拉斯平滑系数** 。

$$
P(F_1 | C) = \frac{N_i + \alpha}{N + \alpha m}
$$

其中，$\alpha$ 为指定的系数，一般为 1. m 为训练文档中统计出的特征词个数。

这样，娱乐类的计算方式就变为：

$$
P(\text{影院，支付宝，云计算} | \text{娱乐}) \cdot P(\text{娱乐}) = \frac{56 + 1}{121 + 1 \cdot 4} \cdot \frac{15 + 1}{121 + 1 \cdot 4} \cdot \frac{0 + 1}{121 + 1 \cdot 4} \cdot (\frac{121}{221}) = 0.001
$$

注意，**科技类的计算方式也需要进行拉普拉斯**。

In [9]:
"""
朴素贝叶斯进行文本分类
:return: None
"""
news = fetch_20newsgroups(subset='all', data_home='data')

print(len(news.data))
print(news.target)
print(news.target_names)


18846
[10  3 17 ...  3  1  7]
['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [10]:
# 进行数据分割
x_train, x_test, y_train, y_test = train_test_split(news.data, news.target, test_size=0.25, random_state=1)

# 对数据集进行特征抽取
tf = TfidfVectorizer()

# 以训练集当中的词的列表进行每篇文章重要性统计['a','b','c','d']
x_train = tf.fit_transform(x_train)

# print(tf.get_feature_names())

x_test = tf.transform(x_test)

# 进行朴素贝叶斯算法的预测,alpha是拉普拉斯平滑系数，分子和分母加上一个系数，分母加alpha*特征词数目
mlt = MultinomialNB(alpha=1.0)

print(x_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
# 训练
mlt.fit(x_train, y_train)

y_predict = mlt.predict(x_test)

print("预测的文章类别为：", y_predict)

# 得出准确率,这个是很难提高准确率，为什么呢？
print("准确率为：", mlt.score(x_test, y_test))
# 目前这个场景我们不需要召回率，support是划分为那个类别的有多少个样本
print("每个类别的精确率和召回率：", classification_report(y_test, y_predict, target_names=news.target_names))

预测的文章类别为： [16 19 18 ... 13  7 14]
准确率为： 0.8518675721561969
每个类别的精确率和召回率：                           precision    recall  f1-score   support

             alt.atheism       0.91      0.77      0.83       199
           comp.graphics       0.83      0.79      0.81       242
 comp.os.ms-windows.misc       0.89      0.83      0.86       263
comp.sys.ibm.pc.hardware       0.80      0.83      0.81       262
   comp.sys.mac.hardware       0.90      0.88      0.89       234
          comp.windows.x       0.92      0.85      0.88       230
            misc.forsale       0.96      0.67      0.79       257
               rec.autos       0.90      0.87      0.88       265
         rec.motorcycles       0.90      0.95      0.92       251
      rec.sport.baseball       0.89      0.96      0.93       226
        rec.sport.hockey       0.95      0.98      0.96       262
               sci.crypt       0.76      0.97      0.85       257
         sci.electronics       0.84      0.80      0.82       229
  

In [12]:
# 把0-19总计20个分类，变为0和1
y_test = np.where(y_test == 0, 1, 0) # 0 改成 1,其他的改成 0，这样就转化为二分类了
y_predict = np.where(y_predict == 0, 1, 0)
# roc_auc_score的y_test只能是二分类,针对多分类如何计算AUC
print("AUC指标：", roc_auc_score(y_test, y_predict))

AUC指标： 0.8827602448315142


In [13]:
# del x_train
# del x_test
# del y_test
# del y_predict
print(tf.get_feature_names_out())
len(tf.get_feature_names_out())

['00' '000' '0000' ... 'ñaustin' 'ýé' 'ÿhooked']


153196